set(_AMENT_PACKAGE_NAME "scan_planner_msgs")
set(scan_planner_msgs_VERSION "0.1.0")
set(scan_planner_msgs_MAINTAINER "SCAN-Planner maintainers <iszhouxin@zju.edu.cn>")
set(scan_planner_msgs_BUILD_DEPENDS "builtin_interfaces" "geometry_msgs" "std_msgs")
set(scan_planner_msgs_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(scan_planner_msgs_BUILD_EXPORT_DEPENDS "builtin_interfaces" "geometry_msgs" "std_msgs")
set(scan_planner_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(scan_planner_msgs_EXEC_DEPENDS "rosidl_default_runtime" "builtin_interfaces" "geometry_msgs" "std_msgs")
set(scan_planner_msgs_TEST_DEPENDS )
set(scan_planner_msgs_GROUP_DEPENDS )
set(scan_planner_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(scan_planner_msgs_DEPRECATED "")
set(scan_planner_msgs_EXPORT_TAGS)
list(APPEND scan_planner_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
