set(_AMENT_PACKAGE_NAME "sentry_scan_adapter_cpp")
set(sentry_scan_adapter_cpp_VERSION "0.1.0")
set(sentry_scan_adapter_cpp_MAINTAINER "adapt_VI_26_Sentry <dev@example.com>")
set(sentry_scan_adapter_cpp_BUILD_DEPENDS "rclcpp" "nav_msgs" "sensor_msgs" "geometry_msgs" "diagnostic_msgs" "std_msgs" "tf2" "tf2_ros" "tf2_geometry_msgs" "pcl_conversions" "scan_planner_msgs" "eigen")
set(sentry_scan_adapter_cpp_BUILDTOOL_DEPENDS "ament_cmake")
set(sentry_scan_adapter_cpp_BUILD_EXPORT_DEPENDS "rclcpp" "nav_msgs" "sensor_msgs" "geometry_msgs" "diagnostic_msgs" "std_msgs" "tf2" "tf2_ros" "tf2_geometry_msgs" "pcl_conversions" "scan_planner_msgs" "eigen")
set(sentry_scan_adapter_cpp_BUILDTOOL_EXPORT_DEPENDS )
set(sentry_scan_adapter_cpp_EXEC_DEPENDS "rclcpp" "nav_msgs" "sensor_msgs" "geometry_msgs" "diagnostic_msgs" "std_msgs" "tf2" "tf2_ros" "tf2_geometry_msgs" "pcl_conversions" "scan_planner_msgs" "eigen")
set(sentry_scan_adapter_cpp_TEST_DEPENDS )
set(sentry_scan_adapter_cpp_GROUP_DEPENDS )
set(sentry_scan_adapter_cpp_MEMBER_OF_GROUPS )
set(sentry_scan_adapter_cpp_DEPRECATED "")
set(sentry_scan_adapter_cpp_EXPORT_TAGS)
list(APPEND sentry_scan_adapter_cpp_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
